{
 "title": "Paygate",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Transfers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transfer transaction request",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "rate(paygate_transaction_transfer_transaction_request_total[30s])"
      }
     ]
    },
    {
     "title": "Transfer transaction pooling request",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
     "targets": [
      {
       "expr": "rate(paygate_transaction_transfer_transaction_pooling_request_total[30s])"
      }
     ]
    },
    {
     "title": "Transfer transaction success",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
     "targets": [
      {
       "expr": "rate(paygate_transaction_transfer_transaction_success_total[30s])"
      }
     ]
    },
    {
     "title": "Transfer transaction pooling success",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "rate(paygate_transaction_transfer_transaction_pooling_success_total[30s])"
      }
     ]
    },
    {
     "title": "Transfer transaction pooling failed",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
     "targets": [
      {
       "expr": "rate(paygate_transaction_transfer_transaction_pooling_failed_total[30s])"
      }
     ]
    },
    {
     "title": "Transfer transaction pooling error",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
     "targets": [
      {
       "expr": "rate(paygate_transaction_transfer_transaction_pooling_error_total[30s])"
      }
     ]
    },
    {
     "title": "Transfer transaction pooling pending",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "rate(paygate_transaction_transfer_transaction_pooling_pending_total[30s])"
      }
     ]
    },
    {
     "title": "Transfer transaction failed",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 9 },
     "targets": [
      {
       "expr": "rate(paygate_transaction_transfer_transaction_failed_total[30s])"
      }
     ]
    },
    {
     "title": "Transfer transaction undefined",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 9 },
     "targets": [
      {
       "expr": "rate(paygate_transaction_transfer_transaction_undefined_total[30s])"
      }
     ]
    },
    {
     "title": "Transfer transaction error",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "rate(paygate_transaction_transfer_transaction_error_total[30s])"
      }
     ]
    },
    {
     "title": "Transfer retry",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 13 },
     "targets": [
      {
       "expr": "rate(paygate_transaction_transfer_retry_total[30s])"
      }
     ]
    }
   ]
  },
  {
   "title": "Transfers API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transfer request success",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "rate(paygate_transaction_api_transfer_success_response_total[30s])"
      }
     ]
    },
    {
     "title": "Transfer too_many_requests error",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 2 },
     "targets": [
      {
       "expr": "rate(paygate_transaction_api_transfer_too_many_requests_response_total[30s])"
      }
     ]
    },
    {
     "title": "Transfer request currency_invalid error",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 2 },
     "targets": [
      {
       "expr": "rate(paygate_transaction_api_transfer_currency_invalid_response_total[30s])"
      }
     ]
    },
    {
     "title": "Transfer request service_down error",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "rate(paygate_transaction_api_transfer_service_down_response_total[30s])"
      }
     ]
    },
    {
     "title": "Transfer request token_service_down error",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
     "targets": [
      {
       "expr": "rate(paygate_transaction_api_transfer_token_service_down_response_total[30s])"
      }
     ]
    },
    {
     "title": "Transfer request unknown error",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 6 },
     "targets": [
      {
       "expr": "rate(paygate_transaction_api_transfer_unknown_response_total[30s])"
      }
     ]
    }
   ]
  }
 ]
}